### PR TITLE
//WIP: Charts of different repos are mixed

### LINKED ISSUE #21: Charts of different repos are mixed
Hi,
thanks for developing this fork until the feature is merged to core!

I found a bug, when a chart with the same name is part of multiple added repos. The logic seems to "mix" the charts and shows a update for a installed release where no never version is available.

Example:

I have the following repos configured:
```
$ helm repo list
elastic       https://helm.elastic.co
stable      	https://kubernetes-charts.storage.googleapis.com
bitnami     	https://charts.bitnami.com/bitnami
```

I installed the "minio" chart from the "bitnami" repo:
```
$ helm list
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION
minio	minio    	2       	2020-01-06 19:15:42.862116066 +0100 CET	deployed	minio-2.2.0	2019.10.12
```

The newest version of this chart in "bitnami" is `2.2.0` as installed. In the "stable" repo the newest version is `5.0.4`.

This plugin shows an update for minio:
```
$ helm whatup
NAME         	NAMESPACE     	INSTALLED VERSION	LATEST VERSION	CHART        
minio        	minio         	2.2.0            	5.0.4         	minio
```

The same happens for the "elasticsearch" chart (installed from elastic-repo, newer version available in bitnami-repo).

Maybe someone can look into it, what is going wrong here. Thanks! :)

### PR DESCRIPTION
**Pull request by l0nax**
Fixes #21

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -241,11 +258,14 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
 
 	if !found {
 		debug("Could not find any Repo which contains %s", name)
-		return nil, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
+		return nil, false, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
```
Comment (l0nax) [inline main.go]: Codacy Issue found: [should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

**Comment by l0nax** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- main.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442&bid=16123740)

**Comment by l0nax** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- main.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442&bid=16123740)

File: main.go [hunk 2]
```diff
@@ -222,14 +230,31 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
...
 				name, chartVersion, result.Name, result.Chart.Metadata.Version)
 			debug("Using '%s' as constrain against '%s'", constrainStr, result.Chart.Metadata.Version)
 			if constrain.Check(version) {
-				return result, nil
+				// only return if 'deprecationInfo' is set to false
+				// because then we do not have to chec if there
+				// are deprecated repositories.
+				if !deprecationInfo {
+					return result, false, nil
+				} else {
```
Comment (l0nax) [inline main.go]: Codacy Issue found: [if block ends with a return statement, so drop this else and outdent its block](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

File: main.go [hunk 3]
```diff
@@ -241,11 +266,21 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
 
 	if !found {
 		debug("Could not find any Repo which contains %s", name)
-		return nil, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
+		return nil, false, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
```
Comment (l0nax) [inline main.go]: Codacy Issue found: [should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

File: main.go [hunk 4]
```diff
@@ -199,8 +201,14 @@ func initSearch(out io.Writer, o *searchRepoOptions) (*search.Index, error) {
...
 // If no results are found, nil will be returned instead of type *Result.
-func searchChart(r []*search.Result, name string, chartVersion string, devel bool) (*search.Result, error) {
-	found := false // found describres if Charts where found but no one is newer than the actual one
+// And the bool describes if it may be some Repositories contain a deprecated chart.
+func searchChart(r []*search.Result, name string, chartVersion string, devel bool) (*search.Result, bool, error) {
+	//  since we have now to check also if a repository contains an
+	// deprecated chart we need an "point" where to look if we have found
+	// a newer chart version
+	foundNewer := false
+	found := false                 // found describres if Charts where found but no one is newer than the actual one
```
Comment (nvanheuverzwijn) [inline main.go]: Typo in comments : "describres" should be "describes"

**Review by nvanheuverzwijn — CHANGES_REQUESTED** [review]
**On line 162 of main.go**
`repoResult, err := searchChart(results, r.Chart.Name(), r.Chart.Metadata.Version, devel)` searchChart now returns 3 parameter.

**Comment by nvanheuverzwijn** [comment]
@l0nax I don't know if you are still working on this but it seems that this patch break completely helm whatup. I don't have any more output when I run `helm-whatup -A` !

**Comment by nvanheuverzwijn** [comment]
Oh nevermind my last comment, I can see why !

**Comment by l0nax** [comment]
> @l0nax I don't know if you are still working on this but it seems that this patch break completely helm whatup. I don't have any more output when I run `helm-whatup -A` !

Yes I'm working on this fix but I have much internal work currently, so I will start working on this ASAP :D

File: main.go (hunk 4 above)
Comment (l0nax) [reply main.go]: FIxed with Commit 7db5c50ad510425a3586ff62afdde7c98d50c514

**Comment by l0nax** [comment]
I would appreciate if someone could help me :)

**Comment by l0nax** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- main.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442&bid=16123740)

File: main.go [hunk 5]
```diff
@@ -241,11 +267,21 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
 
 	if !found {
 		debug("Could not find any Repo which contains %s", name)
-		return nil, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
+		return nil, false, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
```
Comment (l0nax) [inline main.go]: Codacy Issue found: [should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

File: main.go [hunk 6]
```diff
@@ -222,14 +231,31 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
...
 				name, chartVersion, result.Name, result.Chart.Metadata.Version)
 			debug("Using '%s' as constrain against '%s'", constrainStr, result.Chart.Metadata.Version)
 			if constrain.Check(version) {
-				return result, nil
+				// only return if 'deprecationInfo' is set to false
+				// because then we do not have to chec if there
+				// are deprecated repositories.
+				if !deprecationInfo {
+					return result, false, nil
+				} else {
```
Comment (l0nax) [inline main.go]: Codacy Issue found: [if block ends with a return statement, so drop this else and outdent its block](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

**Comment by l0nax** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- main.go  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442&bid=16123740)

File: main.go [hunk 7]
```diff
@@ -222,14 +236,31 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
...
```
Comment (l0nax) [inline main.go]: Codacy found an issue: [if block ends with a return statement, so drop this else and outdent its block](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

File: main.go [hunk 8]
```diff
@@ -66,6 +67,11 @@ with the '--output' Flag.
 `
 
 var ignoreNoRepo bool = false
+var showVersion bool = false
```
Comment (l0nax) [inline main.go]: Codacy found an issue: [should omit type bool from declaration of var showVersion; it will be inferred from the right-hand side](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)

File: main.go [hunk 9]
```diff
@@ -241,11 +272,21 @@ func searchChart(r []*search.Result, name string, chartVersion string, devel boo
 
 	if !found {
 		debug("Could not find any Repo which contains %s", name)
-		return nil, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
+		return nil, false, errors.New(fmt.Sprintf("Could not find any Repo which contains %s", name))
```
Comment (l0nax) [inline main.go]: Codacy found an issue: [should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)](https://app.codacy.com/manual/l0nax/helm-whatup/pullRequest?prid=4860442)
